[tool.poetry]
name = "recorder-module-3"
version = "0.1.0"
description = ""
authors = ["pikamonvvs <pikamonvvs@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ffmpeg-python = "^0.2.0"
requests = "^2.32.3"
tiktokapi = "^6.3.0"
tiktoklive = "^6.0.6"
bs4 = "^0.0.2"
types-requests = "^2.32.0.20240622"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
